/* Generated By:JJTree: Do not edit this line. ASTactual_parameter_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTactual_parameter_list extends SimpleNode {
  public ASTactual_parameter_list(int id) {
    super(id);
  }

  public ASTactual_parameter_list(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cd244dc7b8ab2f7864b9a18863d5f3a1 (do not edit this line) */
