/* Generated By:JJTree: Do not edit this line. ASTAdditionNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTAdditionNode extends SimpleNode {
  public ASTAdditionNode(int id) {
    super(id);
  }

  public ASTAdditionNode(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f7c74dca708b9f358f5d71c2919a6da9 (do not edit this line) */
