/* Generated By:JJTree: Do not edit this line. ASTarray_variable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTarray_variable extends SimpleNode {
  public ASTarray_variable(int id) {
    super(id);
  }

  public ASTarray_variable(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1c43f00c4b1dd7eb97d6357e1f1050d4 (do not edit this line) */
