/* Generated By:JJTree: Do not edit this line. ASTactual_parameter_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

import java.util.ArrayList;

import codeGenerator.Component;
import codeGenerator.GenerateException;
import codeGenerator.GeneratorContext;
import codeGenerator.Type;

public
class ASTactual_parameter_list extends SimpleNode {
  public ASTactual_parameter_list(int id) {
    super(id);
  }

  public ASTactual_parameter_list(Pascal p, int id) {
    super(p, id);
  }
  
  public ArrayList<Type> getParameterList(GeneratorContext gc) throws GenerateException{
	  if (children!=null) {
		  ArrayList<Type> ac=new ArrayList<Type>();
		  for (int i=0;i<children.length;++i) {
			  if (children[i]!=null && children[i] instanceof ASTactual_parameter) {
				  ASTactual_parameter aap = (ASTactual_parameter)children[i];
				  aap.addParameter(gc,ac);
			  }
		  }
		  return ac;
	  }
	  throw new GenerateException("Something Very Bad!\n");
  }

}
/* JavaCC - OriginalChecksum=cd244dc7b8ab2f7864b9a18863d5f3a1 (do not edit this line) */
