/* Generated By:JJTree: Do not edit this line. ASTactual_parameter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTactual_parameter extends SimpleNode {
  public ASTactual_parameter(int id) {
    super(id);
  }

  public ASTactual_parameter(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ef924997a61ffb8bab482811742ce31b (do not edit this line) */
