/* Generated By:JJTree: Do not edit this line. ASTassignment_statement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTassignment_statement extends SimpleNode {
  public ASTassignment_statement(int id) {
    super(id);
  }

  public ASTassignment_statement(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=de7126c8ff1c682fb16a608187cf70f9 (do not edit this line) */
