/* Generated By:JJTree: Do not edit this line. ASTactual_variable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTactual_variable extends SimpleNode {
  public ASTactual_variable(int id) {
    super(id);
  }

  public ASTactual_variable(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9e63b4df853cfbe1350872b1b005ed40 (do not edit this line) */
