/* Generated By:JJTree: Do not edit this line. ASTarray_type.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTarray_type extends SimpleNode {
  public ASTarray_type(int id) {
    super(id);
  }

  public ASTarray_type(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7a67015b31de91bc935544fe352f087e (do not edit this line) */
