/* Generated By:JJTree: Do not edit this line. ASTactual_value.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTactual_value extends SimpleNode {
  public ASTactual_value(int id) {
    super(id);
  }

  public ASTactual_value(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b8198e4f0aea3dcb0d8313978d0a285e (do not edit this line) */
