/* Generated By:JJTree: Do not edit this line. ASTaddition_operator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTaddition_operator extends SimpleNode {
	private String opt;
  public ASTaddition_operator(int id) {
    super(id);
  }

  public ASTaddition_operator(Pascal p, int id) {
    super(p, id);
  }
  
  public void setOpt(String o) {
	  opt=o;
  }
  public String toString() { return "additional_operator \"" + opt +"\"";}

}
/* JavaCC - OriginalChecksum=4724cdf73751deb9c36b4caaa1499151 (do not edit this line) */
