/* Generated By:JJTree: Do not edit this line. ASTbound_specification.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTbound_specification extends SimpleNode {
  public ASTbound_specification(int id) {
    super(id);
  }

  public ASTbound_specification(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ec7a85154e61a2674e02f0fcc07df96b (do not edit this line) */
