/* Generated By:JJTree: Do not edit this line. ASTbound_identifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTbound_identifier extends SimpleNode {
  public ASTbound_identifier(int id) {
    super(id);
  }

  public ASTbound_identifier(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4bee68ca89bc2a54f786d5f83b094beb (do not edit this line) */
