/* Generated By:JJTree: Do not edit this line. ASTblock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTblock extends SimpleNode {
  public ASTblock(int id) {
    super(id);
  }

  public ASTblock(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d6a9bdbf2c71abfa7dd6aa47adbf7ad2 (do not edit this line) */
