/* Generated By:JJTree: Do not edit this line. ASTconstant_definition_part.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTconstant_definition_part extends SimpleNode {
  public ASTconstant_definition_part(int id) {
    super(id);
  }

  public ASTconstant_definition_part(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bbac34b4a25322268478ad8c6214a582 (do not edit this line) */
