/* Generated By:JJTree: Do not edit this line. ASTcase_statement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTcase_statement extends SimpleNode {
  public ASTcase_statement(int id) {
    super(id);
  }

  public ASTcase_statement(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f632ed5d623328b81ef0fad958aaf9d0 (do not edit this line) */
