/* Generated By:JJTree: Do not edit this line. ASTconstant_identifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTconstant_identifier extends SimpleNode {
  public ASTconstant_identifier(int id) {
    super(id);
  }

  public ASTconstant_identifier(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9d115f6cef0cdead284befcabfff8ffa (do not edit this line) */
