/* Generated By:JJTree: Do not edit this line. ASTcompound_statement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTcompound_statement extends SimpleNode {
  public ASTcompound_statement(int id) {
    super(id);
  }

  public ASTcompound_statement(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=39f84abe7a854a7d8ea4d11e31c29803 (do not edit this line) */
