/* Generated By:JJTree: Do not edit this line. ASTconstant_definition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTconstant_definition extends SimpleNode {
  public ASTconstant_definition(int id) {
    super(id);
  }

  public ASTconstant_definition(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=107eca1cabbc88141756aebfa458abd4 (do not edit this line) */
