/* Generated By:JJTree: Do not edit this line. ASTcase_limb.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTcase_limb extends SimpleNode {
  public ASTcase_limb(int id) {
    super(id);
  }

  public ASTcase_limb(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5565ffcdc1dcd0349452c1371ddcf47f (do not edit this line) */
