/* Generated By:JJTree: Do not edit this line. ASTconstant.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTconstant extends SimpleNode {
  public ASTconstant(int id) {
    super(id);
  }

  public ASTconstant(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ad8f20ea115e11abfda4faa1ba941602 (do not edit this line) */
