/* Generated By:JJTree: Do not edit this line. ASTconformant_array_schema.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTconformant_array_schema extends SimpleNode {
  public ASTconformant_array_schema(int id) {
    super(id);
  }

  public ASTconformant_array_schema(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8bffd3e69831a89523e1730f1b9758dd (do not edit this line) */
