/* Generated By:JJTree: Do not edit this line. ASTcase_label_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTcase_label_list extends SimpleNode {
  public ASTcase_label_list(int id) {
    super(id);
  }

  public ASTcase_label_list(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=93024350cc5db6f105c8c8f16cd50553 (do not edit this line) */
