/* Generated By:JJTree: Do not edit this line. ASTdeclaration_part.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTdeclaration_part extends SimpleNode {
  public ASTdeclaration_part(int id) {
    super(id);
  }

  public ASTdeclaration_part(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=10c3ec8b83b90b1901645e36daf72dea (do not edit this line) */
