/* Generated By:JJTree: Do not edit this line. ASTexpression_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTexpression_list extends SimpleNode {
  public ASTexpression_list(int id) {
    super(id);
  }

  public ASTexpression_list(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=21f243e3322ce7bf2e7c498fc325ae2b (do not edit this line) */
