/* Generated By:JJTree: Do not edit this line. ASTfunction_identifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTfunction_identifier extends SimpleNode {
  public ASTfunction_identifier(int id) {
    super(id);
  }

  public ASTfunction_identifier(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4a4866c504d143ee6746a5bc96ed24e3 (do not edit this line) */
