/* Generated By:JJTree: Do not edit this line. ASTfield_identifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTfield_identifier extends SimpleNode {
  public ASTfield_identifier(int id) {
    super(id);
  }

  public ASTfield_identifier(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=72eb7d3b36a951f8d3730d7b22561a88 (do not edit this line) */
