/* Generated By:JJTree: Do not edit this line. ASTfunction_designator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTfunction_designator extends SimpleNode {
  public ASTfunction_designator(int id) {
    super(id);
  }

  public ASTfunction_designator(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e38c29b33dd5332502ab135768eab6ba (do not edit this line) */
