/* Generated By:JJTree: Do not edit this line. ASTfield_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTfield_list extends SimpleNode {
  public ASTfield_list(int id) {
    super(id);
  }

  public ASTfield_list(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7cdbc17d6fd84411682d71a478414d0f (do not edit this line) */
