/* Generated By:JJTree: Do not edit this line. ASTfunction_declaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTfunction_declaration extends SimpleNode {
  public ASTfunction_declaration(int id) {
    super(id);
  }

  public ASTfunction_declaration(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c0e4ec63945c6eef063c3ba4638ba0cb (do not edit this line) */
