/* Generated By:JJTree: Do not edit this line. ASTfunction_body.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTfunction_body extends SimpleNode {
  public ASTfunction_body(int id) {
    super(id);
  }

  public ASTfunction_body(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4af26cf8571b5d93228abc6ff08a4845 (do not edit this line) */
