/* Generated By:JJTree: Do not edit this line. ASTfor_statement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTfor_statement extends SimpleNode {
  public ASTfor_statement(int id) {
    super(id);
  }

  public ASTfor_statement(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0a0ccd1a850f9d355b9be6f86efb1f46 (do not edit this line) */
