/* Generated By:JJTree: Do not edit this line. ASTfinal_expression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTfinal_expression extends SimpleNode {
  public ASTfinal_expression(int id) {
    super(id);
  }

  public ASTfinal_expression(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=831d2451c6e4956a83572c0803774ae0 (do not edit this line) */
