/* Generated By:JJTree: Do not edit this line. ASTformal_parameter_section.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTformal_parameter_section extends SimpleNode {
  public ASTformal_parameter_section(int id) {
    super(id);
  }

  public ASTformal_parameter_section(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=20d2bbb16cb23a1e5a4015480cdce667 (do not edit this line) */
