/* Generated By:JJTree: Do not edit this line. ASTformal_parameter_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTformal_parameter_list extends SimpleNode {
  public ASTformal_parameter_list(int id) {
    super(id);
  }

  public ASTformal_parameter_list(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0c3af72019598e62d23230c4e9b2e972 (do not edit this line) */
