/* Generated By:JJTree: Do not edit this line. ASTfactor.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTfactor extends SimpleNode {
  public ASTfactor(int id) {
    super(id);
  }

  public ASTfactor(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=76499624d73485416cc661318ccbcce2 (do not edit this line) */
