/* Generated By:JJTree: Do not edit this line. ASTfunction_heading.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTfunction_heading extends SimpleNode {
  public ASTfunction_heading(int id) {
    super(id);
  }

  public ASTfunction_heading(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=387f0341d4df9ca7710cb6a2e9065e4a (do not edit this line) */
