/* Generated By:JJTree: Do not edit this line. ASTfixed_part.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTfixed_part extends SimpleNode {
  public ASTfixed_part(int id) {
    super(id);
  }

  public ASTfixed_part(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6021218dec94c631b2aa45a0ba940a67 (do not edit this line) */
