/* Generated By:JJTree: Do not edit this line. ASTinitial_expression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTinitial_expression extends SimpleNode {
  public ASTinitial_expression(int id) {
    super(id);
  }

  public ASTinitial_expression(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e16489e56f8ab8bb65777da49f2bc089 (do not edit this line) */
