/* Generated By:JJTree: Do not edit this line. ASTidentifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTidentifier extends SimpleNode {
	private String name;
  public ASTidentifier(int id) {
    super(id);
  }

  public ASTidentifier(Pascal p, int id) {
    super(p, id);
  }
 
  public void setName(String n) {
	  name=n;
  }
  public String toString() {
	  return "<Identifier>: "+name;
  }

}
/* JavaCC - OriginalChecksum=0000c832ae6bc82805325dab47a1532e (do not edit this line) */
