/* Generated By:JJTree: Do not edit this line. ASTinput_statement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

import codeGenerator.GenerateException;
import codeGenerator.GeneratorContext;

public
class ASTinput_statement extends SimpleNode {
  public ASTinput_statement(int id) {
    super(id);
  }

  public ASTinput_statement(Pascal p, int id) {
    super(p, id);
  }

  public Object generateCode(GeneratorContext gc) throws GenerateException{
	  if (gc.generate) {
		  if (children!=null && children.length==1 && children[0] instanceof ASTinput_list) {
			  ASTinput_list aol=(ASTinput_list)children[0];
			  gc.code.append("push rax\n");
			  gc.code.append("push rbx\n");
			  gc.code.append("push rcx\n");
			  gc.code.append("push rdx\n");
			  aol.generateCode(gc);
			  gc.code.append("pop rdx\n");
			  gc.code.append("pop rcx\n");
			  gc.code.append("pop rbx\n");
			  gc.code.append("pop rax\n");
		  }
	  } else {
		  simpleGenerate(gc);
	  }
	  return null;
  }
}
/* JavaCC - OriginalChecksum=bf753d7807a9e400a4bb630a21cc8ef1 (do not edit this line) */
