/* Generated By:JJTree: Do not edit this line. ASTinput_statement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTinput_statement extends SimpleNode {
  public ASTinput_statement(int id) {
    super(id);
  }

  public ASTinput_statement(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bf753d7807a9e400a4bb630a21cc8ef1 (do not edit this line) */
