/* Generated By:JJTree: Do not edit this line. ASTinteger_number.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTinteger_number extends SimpleNode {
	private String num;
  public ASTinteger_number(int id) {
    super(id);
  }

  public ASTinteger_number(Pascal p, int id) {
    super(p, id);
  }
  public void setNum(String n) {
	  num=n;
  }
  
  public String toString() { return "<Integer>: "+num; }
}
/* JavaCC - OriginalChecksum=2f9e29af78f1d0fa1ccd6e8cd4fee6b1 (do not edit this line) */
