/* Generated By:JJTree: Do not edit this line. ASTio_statement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTio_statement extends SimpleNode {
  public ASTio_statement(int id) {
    super(id);
  }

  public ASTio_statement(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=524cac8f215a277eb1f91a3bb055d17c (do not edit this line) */
