/* Generated By:JJTree: Do not edit this line. ASTindexed_suffix.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTindexed_suffix extends SimpleNode {
  public ASTindexed_suffix(int id) {
    super(id);
  }

  public ASTindexed_suffix(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c38ca9573798bd977ade168ec43ffda4 (do not edit this line) */
