/* Generated By:JJTree: Do not edit this line. ASTindex_type.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTindex_type extends SimpleNode {
  public ASTindex_type(int id) {
    super(id);
  }

  public ASTindex_type(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3114444cdbfc946fbf38cbe77b4ed1a3 (do not edit this line) */
