/* Generated By:JJTree: Do not edit this line. ASTlower_bound.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTlower_bound extends SimpleNode {
  public ASTlower_bound(int id) {
    super(id);
  }

  public ASTlower_bound(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9ec46028cb5a12808e0830abe48b6743 (do not edit this line) */
