/* Generated By:JJTree: Do not edit this line. ASTMultiplicationNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTMultiplicationNode extends SimpleNode {
  public ASTMultiplicationNode(int id) {
    super(id);
  }

  public ASTMultiplicationNode(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=35cddcee5d5c59f5ba3a830253b2b4f4 (do not edit this line) */
