/* Generated By:JJTree: Do not edit this line. ASToutput_value.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASToutput_value extends SimpleNode {
  public ASToutput_value(int id) {
    super(id);
  }

  public ASToutput_value(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=49c8668da7759273353b3a7b80724cb4 (do not edit this line) */
