/* Generated By:JJTree: Do not edit this line. ASTordinal_type_identifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTordinal_type_identifier extends SimpleNode {
  public ASTordinal_type_identifier(int id) {
    super(id);
  }

  public ASTordinal_type_identifier(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5341db0fe4ce368f3961650cac977b6f (do not edit this line) */
