/* Generated By:JJTree: Do not edit this line. ASToutput_statement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASToutput_statement extends SimpleNode {
  public ASToutput_statement(int id) {
    super(id);
  }

  public ASToutput_statement(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cb1119a19d5629fadcd60af88a77c743 (do not edit this line) */
