/* Generated By:JJTree: Do not edit this line. ASToutput_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASToutput_list extends SimpleNode {
  public ASToutput_list(int id) {
    super(id);
  }

  public ASToutput_list(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e2b28f87e0207cdd58cd7852cea8726d (do not edit this line) */
