/* Generated By:JJTree: Do not edit this line. ASTprocedure_heading.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTprocedure_heading extends SimpleNode {
  public ASTprocedure_heading(int id) {
    super(id);
  }

  public ASTprocedure_heading(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2000b64b32b346b0a33476a42c73901f (do not edit this line) */
