/* Generated By:JJTree: Do not edit this line. ASTprocedure_identifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTprocedure_identifier extends SimpleNode {
  public ASTprocedure_identifier(int id) {
    super(id);
  }

  public ASTprocedure_identifier(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3824362e601ecabbd36bdb3b6aa49c1d (do not edit this line) */
