/* Generated By:JJTree: Do not edit this line. ASTprocedure_body.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTprocedure_body extends SimpleNode {
  public ASTprocedure_body(int id) {
    super(id);
  }

  public ASTprocedure_body(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=913f4d026e3fa22fbfa2f5f759e47468 (do not edit this line) */
