/* Generated By:JJTree: Do not edit this line. ASTparameter_type.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTparameter_type extends SimpleNode {
  public ASTparameter_type(int id) {
    super(id);
  }

  public ASTparameter_type(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d534ae5db9dbdd0d9cbe852dfbc1cb73 (do not edit this line) */
