/* Generated By:JJTree: Do not edit this line. ASTprocedure_and_function_declaration_part.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTprocedure_and_function_declaration_part extends SimpleNode {
  public ASTprocedure_and_function_declaration_part(int id) {
    super(id);
  }

  public ASTprocedure_and_function_declaration_part(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4b52bd627b81e5a0ba03ec7a38b21e76 (do not edit this line) */
