/* Generated By:JJTree: Do not edit this line. ASTprogram_heading.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTprogram_heading extends SimpleNode {
  public ASTprogram_heading(int id) {
    super(id);
  }

  public ASTprogram_heading(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d2786c403e446826fe967a48382c21ad (do not edit this line) */
