/* Generated By:JJTree: Do not edit this line. ASTRelationNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTRelationNode extends SimpleNode {
  public ASTRelationNode(int id) {
    super(id);
  }

  public ASTRelationNode(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ea6aaab2dea9997ef221f452d90ace02 (do not edit this line) */
