/* Generated By:JJTree: Do not edit this line. ASTrecord_variable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTrecord_variable extends SimpleNode {
  public ASTrecord_variable(int id) {
    super(id);
  }

  public ASTrecord_variable(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=511daa9ba9452f1a2b50c894b00f3cf7 (do not edit this line) */
