/* Generated By:JJTree: Do not edit this line. ASTrepetitive_statement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTrepetitive_statement extends SimpleNode {
  public ASTrepetitive_statement(int id) {
    super(id);
  }

  public ASTrepetitive_statement(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0d585117b561bd10feba62a9f6e31a0d (do not edit this line) */
