/* Generated By:JJTree: Do not edit this line. ASTresult_type.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTresult_type extends SimpleNode {
  public ASTresult_type(int id) {
    super(id);
  }

  public ASTresult_type(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f5682982807a240b1e2e574e3c7a75ee (do not edit this line) */
