/* Generated By:JJTree: Do not edit this line. ASTrepeat_statement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTrepeat_statement extends SimpleNode {
  public ASTrepeat_statement(int id) {
    super(id);
  }

  public ASTrepeat_statement(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=92966b7678e3c34de9847b614d174312 (do not edit this line) */
