/* Generated By:JJTree: Do not edit this line. ASTrecord_section.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTrecord_section extends SimpleNode {
  public ASTrecord_section(int id) {
    super(id);
  }

  public ASTrecord_section(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d247414a6952b1fe8ba82c7e33bc6160 (do not edit this line) */
