/* Generated By:JJTree: Do not edit this line. ASTstatement_part.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTstatement_part extends SimpleNode {
  public ASTstatement_part(int id) {
    super(id);
  }

  public ASTstatement_part(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=10cb6084817fb3d67669359a0a56c5f4 (do not edit this line) */
