/* Generated By:JJTree: Do not edit this line. ASTsimple_type.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTsimple_type extends SimpleNode {
  public ASTsimple_type(int id) {
    super(id);
  }

  public ASTsimple_type(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ef8c37ffdb99ef4c0622a1c3d51cb6ea (do not edit this line) */
