/* Generated By:JJTree: Do not edit this line. ASTstatement_sequence.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTstatement_sequence extends SimpleNode {
  public ASTstatement_sequence(int id) {
    super(id);
  }

  public ASTstatement_sequence(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=852fe43d38dbf3b8e925317102057e43 (do not edit this line) */
