/* Generated By:JJTree: Do not edit this line. ASTsimple_statement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTsimple_statement extends SimpleNode {
  public ASTsimple_statement(int id) {
    super(id);
  }

  public ASTsimple_statement(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9f33bfdbd77cedaef83972a259205447 (do not edit this line) */
