/* Generated By:JJTree: Do not edit this line. ASTsimple_variable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTsimple_variable extends SimpleNode {
  public ASTsimple_variable(int id) {
    super(id);
  }

  public ASTsimple_variable(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=06e17d7a523160cc043fdf1311e4f16f (do not edit this line) */
