/* Generated By:JJTree: Do not edit this line. ASTsign.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTsign extends SimpleNode {
	private String sign;
  public ASTsign(int id) {
    super(id);
  }

  public ASTsign(Pascal p, int id) {
    super(p, id);
  }
  public void setSign(String s) {
	  sign=s;
  }
  
  public String getSign() {
	  return sign;
  }
  public String toString() { return "sign \"" + sign + "\""; }

}
/* JavaCC - OriginalChecksum=1683ed2fb52be3d3698111406af45385 (do not edit this line) */
