/* Generated By:JJTree: Do not edit this line. ASTsimple_expression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTsimple_expression extends SimpleNode {
  public ASTsimple_expression(int id) {
    super(id);
  }

  public ASTsimple_expression(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0252df8f841766d851e359f9a67640c0 (do not edit this line) */
