/* Generated By:JJTree: Do not edit this line. ASTSimpleExpressionNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTSimpleExpressionNode extends SimpleNode {
  public ASTSimpleExpressionNode(int id) {
    super(id);
  }

  public ASTSimpleExpressionNode(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7b3cdace127f812818729496b33ae7d8 (do not edit this line) */
