/* Generated By:JJTree: Do not edit this line. ASTstructured_type.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTstructured_type extends SimpleNode {
  public ASTstructured_type(int id) {
    super(id);
  }

  public ASTstructured_type(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fa1f38292dfc1dc627e3744bf28ca513 (do not edit this line) */
