/* Generated By:JJTree: Do not edit this line. ASTstructured_statement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTstructured_statement extends SimpleNode {
  public ASTstructured_statement(int id) {
    super(id);
  }

  public ASTstructured_statement(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1908845539f2f9b4045362e3d5edc2a6 (do not edit this line) */
