/* Generated By:JJTree: Do not edit this line. ASTtype_definition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTtype_definition extends SimpleNode {
  public ASTtype_definition(int id) {
    super(id);
  }

  public ASTtype_definition(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c629f9519463050ac354e5ee53e5aed0 (do not edit this line) */
