/* Generated By:JJTree: Do not edit this line. ASTtype_definition_part.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTtype_definition_part extends SimpleNode {
  public ASTtype_definition_part(int id) {
    super(id);
  }

  public ASTtype_definition_part(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dd0c7695ac62076d85852e4b4be61da3 (do not edit this line) */
