/* Generated By:JJTree: Do not edit this line. ASTtag_field.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTtag_field extends SimpleNode {
  public ASTtag_field(int id) {
    super(id);
  }

  public ASTtag_field(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=af9203668897fe6eea84566769ddef35 (do not edit this line) */
