/* Generated By:JJTree: Do not edit this line. ASTtype_identifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTtype_identifier extends SimpleNode {
  public ASTtype_identifier(int id) {
    super(id);
  }

  public ASTtype_identifier(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4cec3fe5a06128c2adfc6ceb6cd49494 (do not edit this line) */
