/* Generated By:JJTree: Do not edit this line. ASTTermNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTTermNode extends SimpleNode {
  public ASTTermNode(int id) {
    super(id);
  }

  public ASTTermNode(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d10491b0a476c65b9f0008cb746a9ebd (do not edit this line) */
