/* Generated By:JJTree: Do not edit this line. ASTupper_bound.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTupper_bound extends SimpleNode {
  public ASTupper_bound(int id) {
    super(id);
  }

  public ASTupper_bound(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d299144f88971fb726a22e794cef02b2 (do not edit this line) */
