/* Generated By:JJTree: Do not edit this line. ASTvalue_parameter_section.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTvalue_parameter_section extends SimpleNode {
  public ASTvalue_parameter_section(int id) {
    super(id);
  }

  public ASTvalue_parameter_section(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d2ec33387f2df302fd9a3efea75d1bb7 (do not edit this line) */
