/* Generated By:JJTree: Do not edit this line. ASTvariable_helper.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTvariable_helper extends SimpleNode {
  public ASTvariable_helper(int id) {
    super(id);
  }

  public ASTvariable_helper(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=baa7096d1724fac96472dab94227e54d (do not edit this line) */
