/* Generated By:JJTree: Do not edit this line. ASTvariable_parameter_section.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTvariable_parameter_section extends SimpleNode {
  public ASTvariable_parameter_section(int id) {
    super(id);
  }

  public ASTvariable_parameter_section(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fb39d3d9594add98703d64b9366d8e2c (do not edit this line) */
