/* Generated By:JJTree: Do not edit this line. ASTvariable_declaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTvariable_declaration extends SimpleNode {
  public ASTvariable_declaration(int id) {
    super(id);
  }

  public ASTvariable_declaration(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=79c2fd5b584c3f25d79d9d3f34a8645c (do not edit this line) */
