/* Generated By:JJTree: Do not edit this line. ASTvariable_identifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTvariable_identifier extends SimpleNode {
  public ASTvariable_identifier(int id) {
    super(id);
  }

  public ASTvariable_identifier(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1af0fffe76a7b2ad238951643fd6350d (do not edit this line) */
