/* Generated By:JJTree: Do not edit this line. ASTvariant.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTvariant extends SimpleNode {
  public ASTvariant(int id) {
    super(id);
  }

  public ASTvariant(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dc21d3a146c3a4cb702cc91386927b00 (do not edit this line) */
