/* Generated By:JJTree: Do not edit this line. ASTwhile_statement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTwhile_statement extends SimpleNode {
  public ASTwhile_statement(int id) {
    super(id);
  }

  public ASTwhile_statement(Pascal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=00274aa49cfe1191d8aa48cfb874bc78 (do not edit this line) */
