/* Generated By:JavaCC: Do not edit this line. PascalTreeConstants.java Version 5.0 */
package compiler;

public interface PascalTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTPROGRAM_HEADING = 1;
  public int JJTBLOCK = 2;
  public int JJTDECLARATION_PART = 3;
  public int JJTTYPE_DEFINITION_PART = 4;
  public int JJTTYPE_DEFINITION = 5;
  public int JJTVARIABLE_DECLARATION_PART = 6;
  public int JJTVARIABLE_DECLARATION = 7;
  public int JJTVOID = 8;
  public int JJTPROCEDURE_AND_FUNCTION_DECLARATION_PART = 9;
  public int JJTPROCEDURE_DECLARATION = 10;
  public int JJTPROCEDURE_BODY = 11;
  public int JJTFUNCTION_DECLARATION = 12;
  public int JJTFUNCTION_BODY = 13;
  public int JJTSTATEMENT_PART = 14;
  public int JJTPROCEDURE_HEADING = 15;
  public int JJTFUNCTION_HEADING = 16;
  public int JJTRESULT_TYPE = 17;
  public int JJTFORMAL_PARAMETER_LIST = 18;
  public int JJTFORMAL_PARAMETER_SECTION = 19;
  public int JJTVALUE_PARAMETER_SECTION = 20;
  public int JJTVARIABLE_PARAMETER_SECTION = 21;
  public int JJTSTATEMENT_SEQUENCE = 22;
  public int JJTSTATEMENT = 23;
  public int JJTSIMPLE_STATEMENT = 24;
  public int JJTASSIGNMENT_STATEMENT = 25;
  public int JJTPROCEDURE_STATEMENT = 26;
  public int JJTSTRUCTURED_STATEMENT = 27;
  public int JJTCOMPOUND_STATEMENT = 28;
  public int JJTREPETITIVE_STATEMENT = 29;
  public int JJTWHILE_STATEMENT = 30;
  public int JJTREPEAT_STATEMENT = 31;
  public int JJTFOR_STATEMENT = 32;
  public int JJTINITIAL_EXPRESSION = 33;
  public int JJTFINAL_EXPRESSION = 34;
  public int JJTCONDITIONAL_STATEMENT = 35;
  public int JJTIF_STATEMENT = 36;
  public int JJTCASE_STATEMENT = 37;
  public int JJTCASE_LIMB = 38;
  public int JJTCASE_LABEL_LIST = 39;
  public int JJTACTUAL_PARAMETER_LIST = 40;
  public int JJTACTUAL_PARAMETER = 41;
  public int JJTIO_STATEMENT = 42;
  public int JJTINPUT_STATEMENT = 43;
  public int JJTOUTPUT_STATEMENT = 44;
  public int JJTEXPRESSION = 45;
  public int JJTSIMPLE_EXPRESSION = 46;
  public int JJTADDITIONNODE = 47;
  public int JJTTERM = 48;
  public int JJTMULTIPLICATIONNODE = 49;
  public int JJTFACTOR = 50;
  public int JJTRELATIONAL_OPERATOR = 51;
  public int JJTADDITION_OPERATOR = 52;
  public int JJTMULTIPLICATION_OPERATOR = 53;
  public int JJTVARIABLE = 54;
  public int JJTINDEXED_SUFFIX = 55;
  public int JJTCOMPONENT_SUFFIX = 56;
  public int JJTFUNCTION_DESIGNATOR = 57;
  public int JJTTYPE = 58;
  public int JJTINDEX_TYPE = 59;
  public int JJTLOWER_BOUND = 60;
  public int JJTUPPER_BOUND = 61;
  public int JJTARRAY_TYPE = 62;
  public int JJTRECORD_TYPE = 63;
  public int JJTFIELD_LIST = 64;
  public int JJTRECORD_SECTION = 65;
  public int JJTTAG_FIELD = 66;
  public int JJTOUTPUT_LIST = 67;
  public int JJTOUTPUT_VALUE = 68;
  public int JJTINPUT_LIST = 69;
  public int JJTINPUT_VARIABLE = 70;
  public int JJTRECORD_VARIABLE = 71;
  public int JJTARRAY_VARIABLE = 72;
  public int JJTFIELD_IDENTIFIER = 73;
  public int JJTCONSTANT_IDENTIFIER = 74;
  public int JJTVARIABLE_IDENTIFIER = 75;
  public int JJTTYPE_IDENTIFIER = 76;
  public int JJTPROCEDURE_IDENTIFIER = 77;
  public int JJTBOUND_IDENTIFIER = 78;
  public int JJTIDENTIFIER_LIST = 79;
  public int JJTEXPRESSION_LIST = 80;
  public int JJTNUMBER = 81;
  public int JJTREAL_NUMBER = 82;
  public int JJTINTEGER_NUMBER = 83;
  public int JJTCONSTANT = 84;
  public int JJTSIGN = 85;
  public int JJTIDENTIFIER = 86;


  public String[] jjtNodeName = {
    "program",
    "program_heading",
    "block",
    "declaration_part",
    "type_definition_part",
    "type_definition",
    "variable_declaration_part",
    "variable_declaration",
    "void",
    "procedure_and_function_declaration_part",
    "procedure_declaration",
    "procedure_body",
    "function_declaration",
    "function_body",
    "statement_part",
    "procedure_heading",
    "function_heading",
    "result_type",
    "formal_parameter_list",
    "formal_parameter_section",
    "value_parameter_section",
    "variable_parameter_section",
    "statement_sequence",
    "statement",
    "simple_statement",
    "assignment_statement",
    "procedure_statement",
    "structured_statement",
    "compound_statement",
    "repetitive_statement",
    "while_statement",
    "repeat_statement",
    "for_statement",
    "initial_expression",
    "final_expression",
    "conditional_statement",
    "if_statement",
    "case_statement",
    "case_limb",
    "case_label_list",
    "actual_parameter_list",
    "actual_parameter",
    "io_statement",
    "input_statement",
    "output_statement",
    "expression",
    "simple_expression",
    "AdditionNode",
    "term",
    "MultiplicationNode",
    "factor",
    "relational_operator",
    "addition_operator",
    "multiplication_operator",
    "variable",
    "indexed_suffix",
    "component_suffix",
    "function_designator",
    "type",
    "index_type",
    "lower_bound",
    "upper_bound",
    "array_type",
    "record_type",
    "field_list",
    "record_section",
    "tag_field",
    "output_list",
    "output_value",
    "input_list",
    "input_variable",
    "record_variable",
    "array_variable",
    "field_identifier",
    "constant_identifier",
    "variable_identifier",
    "type_identifier",
    "procedure_identifier",
    "bound_identifier",
    "identifier_list",
    "expression_list",
    "number",
    "real_number",
    "integer_number",
    "constant",
    "sign",
    "identifier",
  };
}
/* JavaCC - OriginalChecksum=b012d7016cedef658c9c2996459e5a47 (do not edit this line) */
